from pylast import (
    PERIOD_7DAYS,
    PERIOD_1MONTH,
    PERIOD_3MONTHS,
    PERIOD_6MONTHS,
    PERIOD_12MONTHS,
    PERIOD_OVERALL,
)

ENTITY_ALBUM = "album"
ENTITY_ARTIST = "artist"
ENTITY_TRACK = "track"
ENTITIES = (ENTITY_ALBUM, ENTITY_ARTIST, ENTITY_TRACK)
PERIODS = (
    PERIOD_7DAYS,
    PERIOD_1MONTH,
    PERIOD_3MONTHS,
    PERIOD_6MONTHS,
    PERIOD_12MONTHS,
    PERIOD_OVERALL,
)

OVERLAY_BANNER = "banner"
OVERLAY_FULL_TINT = "full_tint"
OVERLAY_GRADIENT = "gradient"
OVERLAY_PILL = "pill"
OVERLAY_CLEAN = "clean"
OVERLAY_STYLES = (
    OVERLAY_BANNER,
    OVERLAY_FULL_TINT,
    OVERLAY_GRADIENT,
    OVERLAY_PILL,
    OVERLAY_CLEAN,
)

THEME_DARK = "dark"
THEME_LIGHT = "light"
THEME_GLASSMORPHIC = "glassmorphic"
THEME_SUNSET = "sunset"
THEME_NEON = "neon"
THEMES = (
    THEME_DARK,
    THEME_LIGHT,
    THEME_GLASSMORPHIC,
    THEME_SUNSET,
    THEME_NEON,
)
