from pylast import PERIOD_7DAYS, PERIOD_1MONTH, PERIOD_3MONTHS, PERIOD_6MONTHS, \
    PERIOD_12MONTHS, PERIOD_OVERALL

ENTITY_ALBUM = "album"
ENTITY_ARTIST = "artist"
ENTITY_TRACK = "track"
ENTITIES = (
    ENTITY_ALBUM,
    ENTITY_ARTIST,
    ENTITY_TRACK
)
PERIODS = (
    PERIOD_7DAYS,
    PERIOD_1MONTH,
    PERIOD_3MONTHS,
    PERIOD_6MONTHS,
    PERIOD_12MONTHS,
    PERIOD_OVERALL
)
